name: featherpad # you probably want to 'snapcraft register <name>'
version: '1.3.1'

adopt-info: featherpad
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20
compression: lzo

parts:
  featherpad:
    parse-info:
      - usr/share/metainfo/featherpad.metainfo.xml
    plugin: cmake
    source: https://github.com/tsujan/FeatherPad.git
    source-tag: 'V1.3.1'
    build-packages:
      - libhunspell-dev
      - qtbase5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
    stage-packages:
      - libhunspell-1.7-0
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"


apps:
  featherpad:
    common-id: com.github.FeatherPad
    command: usr/bin/featherpad
    extensions:
      - kde-neon
    plugs:
      - home
